---
# tasks/distro/common.yml: tasks common to all distributions and releases
- name: install time synchronization packages
  package: name={{ item }} state=present
  with_items: "{{ time_sync_packages }}"

- name: render time synchronization configuration
  template:
    src: "{{ time_service_conf_template | default('ntp.conf.j2') }}"
    dest: "{{ time_service_conf_file | default('/etc/ntp.conf') }}"
    owner: root
    group: root
    mode: 0644
  # unfortunately no validation program
  notify: restart time synchronization service

# start and enable the service
- name: start and enable time synchronization service
  service: name={{ time_service_name }} state=started enabled=yes
