---
# load variables per os and release
- name: load ubuntu variables
  include_vars: ubuntu/common.yml
  when: is_ubuntu_derivative

- name: load trusty variables
  include_vars: ubuntu/trusty.yml
  when: is_ubuntu_trusty_derivative

- name: load xenial variables
  include_vars: ubuntu/xenial.yml
  when: is_ubuntu_xenial_derivative

- name: load redhat variables
  include_vars: "{{ var_loop_item }}"
  with_items:
    - redhat/common.yml
    - redhat/rhel7.yml
  loop_control: { loop_var: var_loop_item }
  when: is_redhat_derivative

- name: include systemd facts
  include_tasks: discover/systemd.yml

- name: include sync daemon facts
  include_tasks: discover/sync-daemon.yml

# make sure apt cache is up to date on ubuntu
- name: update cache
  apt: update_cache=yes cache_valid_time=3600
  when: is_ubuntu_derivative
  become: true

# install our time packages if relevant
- name: install time packages
  package: name={{ item }} state=present
  with_items: "{{ time_sync_packages }}"
  become: true

# configure the time sync daemon
- name: configure ntp
  include_tasks: ntp/configure.yml
  when: timesyncd|bool == false

- name: configure timesyncd
  include_tasks: timesyncd/configure.yml
  when: timesyncd|bool

# enable and start the service
- name: start time sync service
  service: name={{ time_service_name }} state=started enabled=yes
  become: true

# configure timedatectl if on systemd
- name: configure timedatectl
  include_tasks: timedatectl/configure.yml
  when: systemd
