---
# load variables per os and release
- name: load ubuntu variables
  include_vars: ubuntu.yml
  when: is_ubuntu_derivative

- name: load redhat variables
  include_vars: redhat.yml
  when: is_redhat_derivative

- name: establish whether systemd
  set_fact:
    systemd: |-
      {{ ansible_service_mgr == "systemd" }}

- name: include sync daemon facts
  include_tasks: discover/sync-daemon.yml

# make sure apt cache is up to date on ubuntu
- name: update cache
  apt: update_cache=yes cache_valid_time=3600
  when: is_ubuntu_derivative
  become: true

# install our time packages if relevant
- name: install time packages
  package: name={{ item }} state=present
  with_items: "{{ time_sync_packages }}"
  become: true

# configure the time sync daemon
- name: configure ntp
  include_tasks: ntp/configure.yml
  when: not timesyncd

- name: configure timesyncd
  include_tasks: timesyncd/configure.yml
  when: timesyncd

# enable and start the service
- name: start time sync service
  service: name={{ time_service_name }} state=started enabled=yes
  become: true

# configure timedatectl if on systemd
- name: configure timedatectl
  include_tasks: timedatectl/configure.yml
  when: systemd
