---
- name: restart ntp
  service: name={{ time_ntp_service_name }} state=restarted
  become: true

- name: restart timesyncd
  service: name={{ time_timesyncd_service_name }} state=restarted
  become: true
